services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: 8112994299:AAG4SE1Pco9lYVnqHTOtO-fg_yvDbmRvTYk
      FILES_DIR: /app/files

    container_name: bot
    restart: unless-stopped
    volumes:
      - .:/app